## Download and install freepbx from source

- name: Remove existing install source dir
  file: "path={{ freepbx_srcdir }} state=absent"

- name: Create install source dir
  file: "path={{ freepbx_srcdir }} state=directory"

- name: Download and extract Freepbx source
  unarchive: "src={{ freepbx_url }} dest={{ freepbx_srcdir }} remote_src=yes extra_opts=--strip-components=1"


- name: Change into freepbx source directory and start asterisk
  shell: ./start_asterisk start
  args:
    chdir: "{{ freepbx_srcdir }}"

- name: Change into freepbx source directory and run install script
  shell: ./install -n --dbuser=root --dbpass="{{ msi_new_mysql_root_pass }}"
  args:
    chdir: "{{ freepbx_srcdir }}"


- name: Update php upload_max_filesize to 120M and update httpd configs.
  block:
    - shell: sed -i 's/\(^upload_max_filesize = \).*/\120M/' /etc/php.ini
    - shell: sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/httpd/conf/httpd.conf
    - shell: sed -i 's/AllowOverride None/AllowOverride All/' /etc/httpd/conf/httpd.conf

- name: Enable Apache/Httpd and Start
  service:
    name: httpd
    enabled: yes
    state: started
